# Generated by Django 3.1.7 on 2021-04-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='book',
            field=models.ManyToManyField(blank=True, related_name='get_book', to='p_library.Book'),
        ),
    ]
