# Generated by Django 3.1.7 on 2021-04-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20210409_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='book',
            field=models.ManyToManyField(related_name='get_book', to='p_library.Book'),
        ),
    ]
