# Generated by Django 3.1.7 on 2021-04-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0003_auto_20210406_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('is_friend', models.BooleanField(default=True)),
                ('book', models.ManyToManyField(related_name='get_book', to='p_library.Book')),
            ],
        ),
    ]
