# Generated by Django 3.1.7 on 2021-04-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0011_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(height_field=200, upload_to='images', width_field=200),
        ),
    ]
