# Generated by Django 3.1.7 on 2021-04-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0012_auto_20210420_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_height',
            field=models.PositiveIntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='cover_width',
            field=models.PositiveIntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(height_field='cover_height', upload_to='images', width_field='cover_width'),
        ),
    ]
